### ISSUE TITLE
pretrain problems

### ISSUE THREAD

**Issue by Henry-Bi** [mlpc-ucsd/TESTR#11]
Hello, I was trying to do pretrain TESTR on my own machine, but it seems that when I train the model and evaluation per 20,000 iterations the evaluation result is always 0. Moreover, when I adopt the pretrain weights and finetune TESTR on my machine, it works well. 
For the config files (../configs/TESTR/Pretrain/TESTR_R_50.yaml), I only adjusted the batch size from 8 to 2 and trained the model on 2GPUs. I hope to get your reply, thank you!

**Comment by ymy-k** [comment]
Hi, I think it's normal. First, the end-to-end result converges slowly with a batch size of 8 from my experiments. Second, the batch size you used is small, the model will need more iterations to get correct results.

**Comment by Henry-Bi** [comment]
> Hi, I think it's normal. First, the end-to-end result converges slowly with a batch size of 8 from my experiments. Second, the batch size you used is small, the model will need more iterations to get correct results.

Thanks for your reply. According to issues of DETR and Deformable DETR, I have reduced the learning rates. The setting of learning rates is vital for training transformer-based models using smaller batch-size.
