### ISSUE TITLE
Did you use other scripts beside Latin in MLT2017 for pre-training?

### ISSUE THREAD

**Issue by rubycheen** [mlpc-ucsd/TESTR#13]
Did you use other scripts beside Latin in MLT2017 for pre-training?

**Comment by zx1239856** [comment]
Our model only works with Latin scripts. You may refer to #12 if you want to extend the character set.

**Comment by rubycheen** [comment]
@zx1239856 Thanks a lot! And I found the coco format data has column "polys" with 16 numbers (8 points?) for each, how did you convert ICDAR dataset that only have bounding box with four points to that?

**Comment by zx1239856** [comment]
The 8 points "polys" are control points of Bezier curves. For polygon annotations, we use 16 points. We reuse this column name for both types of annotations. 

Please refer to https://github.com/mlpc-ucsd/TESTR/blob/main/adet/data/builtin.py#L19-L47. For example, `totaltext_poly_train` is polygonal TotalText, whereas `totaltext_train` is the Bezier variant.

In terms of conversion from quadrilateral boxes to 16-point polygons, I assume you may add 3 more points to each side of the box. I've also seen other approaches based on the division of circumference, i.e. you divide the perimeter into 13 segments evenly and therefore 12 points can be added.

**Comment by rubycheen** [comment]
Thanks! So your illustration is exactly the same with your method of conversion? (divide the perimeter into 13 segments evenly and therefore 12 points can be added)

**Comment by zx1239856** [comment]
We simply adopted the first approach I mentioned above i.e. inserting 3 more points on each side.

**Comment by rubycheen** [comment]
I got it, thank you so much:)
