### ISSUE TITLE
demo using problems（使用demo时的问题）

### ISSUE THREAD

**Issue by lvyongting** [mlpc-ucsd/TESTR#14]
**I use the command** “python demo/demo.py --config-file E:/TESTR-main/configs/TESTR/ICDAR15/TESTR_R_50_Polygon.yaml --input E:/TESTR-main/dataset/icdar2015/test_images/img_204.jpg --output E:/TESTR-main/output/ --opts MODEL.WEIGHTS E:/TESTR-main/models/icdar15_testr_R_50_polygon.pth MODEL.TRANSFORMER.INFERENCE_TH_TEST 0.3” **to run the demo**(that all are my private path)

but the problem always exit : KeyError: 'Non-existent config key: MODEL.TRANSFORMER'

and I don't konw which steps were wrong. If you can help me,I will be very Grateful.

作者您好，我按readme的步骤配置了相关环境，使用demo时一直报：KeyError: 'Non-existent config key: MODEL.TRANSFORMER'
经过一步一步排查，发现函数def _merge_a_into_b(a, b, root, key_list):里面的b没有MODEL.TRANSFORMER项，请问是我config配置错误还是环境安装错误亦或是其他我不知道的错误。

**Comment by lvyongting** [comment]
![image](https://user-images.githubusercontent.com/36529870/201530294-126c7426-9910-47f4-a8d3-db7b6ff1ceb7.png)
the erro

**Comment by zx1239856** [comment]
We're unable to reproduce the issue. 

https://github.com/mlpc-ucsd/TESTR/blob/main/demo/demo.py#L22 
`setup_cfg` uses the default configs from 

https://github.com/mlpc-ucsd/TESTR/blob/43df00d60efb1fcd71372dec70980d1cf54ad1a9/adet/config/defaults.py#L343

which contains `MODEL.TRANSFORMER`.

I guess you may have loaded some other packages (e.g. the official AdelaiDet) and they don't have such config keys.
