### ISSUE TITLE
GPU used for training TESTR

### ISSUE THREAD

**Issue by k-styles** [mlpc-ucsd/TESTR#18]
Hi, thanks for this research paper, pretty amazing work!
I am trying to reproduce your results on Nvidia Tesla V100 32GB, but I ran into CUDA out of memory error.
Could you please let me know, what GPU was used for this research work?

Command used for training on CTW1500 dataset:
```
python tools/train_net.py --config-file configs/TESTR/CTW1500/Base-CTW1500.yaml --num-gpus 1
```

**Comment by zx1239856** [comment]
Try reducing `SOLVER.IMS_PER_BATCH`
