### ISSUE TITLE
About the Datasets

### ISSUE THREAD

**Issue by Pujin823** [mlpc-ucsd/TESTR#19]
hi, thanks for your wonderful work. i want to ask a question about the annotations you have provided. I found that there is a deviation between the annotations you provided and the original annotation. most annotation["polys"] is beyond the annotation["bbox"].  
for example, in the ctw1500_test_1001.jpg, 
annotation["id"] = 1, annotation["img_ids"] = 1001, annotation["bbox"] = [45, 56.6, 90, 27.4]
annotation["polys"] = [45, 73, 64.01, 64.83, 76.64, 59.36, 85.5, 56.61, 93.17, 56.59, 102.24, 59.3, 115.32, 64.77, 135, 73, 130, 84, 111.29, 77.2, 100.05, 72.21, 93.21, 69.31, 87.68, 68.77, 80.36, 70.85, 68.16, 75.84, 48, 84] , 56.59 is less than 56.6. 
annotation["area"] = 1092, not equal with 90x27.4=2466.
and the original annotation["polys"] = [48. 84, 61, 79, 75, 73, 88, 68, 102, 74, 116, 79, 130, 84, 135, 73, 119, 67, 104, 60, 89, 56, 74, 61, 59, 67, 45, 73]
can u explain about that? and if have any script for convert the original annotation to coco format? if you do, can you share it?

**Comment by zx1239856** [comment]
For the Bezier annotation, the bounding polygon of the Bezier curve may well exceed the bounding box.

The script will be posted in #3 once ready.
