### ISSUE TITLE
Shape is invalid for input size

### ISSUE THREAD

**Issue by hao3830** [mlpc-ucsd/TESTR#2]
Hi everyone I'm facing with this problem when I try to run train_net.py:
![image](https://user-images.githubusercontent.com/97509830/163680984-4f9867a2-c643-48bb-a807-ef6045f063d5.png)

What is testr.num_ctrl_points? why it is 16?
I hope to get some suggestions. Thank you a lot.

**Comment by zx1239856** [comment]
Please carefully follow the guidelines and don't mix the Bezier and polygonal annotations. 
We use 8 control points for Bezier and 16 for polygons, and the number is fixed, as mentioned in 
the main paper.
