### ISSUE TITLE
error during demo using video 

### ISSUE THREAD

**Issue by maherr13** [mlpc-ucsd/TESTR#4]
Hi, Great work!

I tried doing inference using images and it worked well, but during the inference using video, I got this error. 

![image](https://user-images.githubusercontent.com/83926003/170272523-8a781f35-4822-4b98-b451-94b972d9ed37.png)

Any thoughts on how to get through it?

**Comment by zx1239856** [comment]
Thanks for your interest.

Currently, we do not have support for video input. The original visualizer in `demo.py` (from AdelaiDet) would require some modifications before it can be used with videos. We recommend you try the image visualizer only.
